resilience4j.circuitbreaker.instances.bookingServiceCB.baseConfig=default

resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

resilience4j.timelimiter.instances.financeServiceCB.baseConfig=default

resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=2s

resilience4j.retry.instances.financeServiceRetry.baseConfig=default

resilience4j.timelimiter.configs.default.timeoutDuration=2s

booking.service.url=http://localhost:8083
